name: 'CI'
on:
  push:
    branches: [wip, main]
    tags:
      - '*'
  pull_request:

jobs:
  build:
    # if: github.event_name  == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test JUnit test import
        uses: ./
        # if: endsWith(github.ref, 'main') == false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Example JUnit Test Report
          report_paths: '**/surefire-reports/TEST-*.xml'
          detailed_summary: true
      - name: Test PyTest test import
        uses: ./
        # if: endsWith(github.ref, 'main') == false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Example Pytest Report
          report_paths: test_results/python/report.xml
          detailed_summary: true
      # - name: Install NPM
      #   run: |
      #     npm install
      # - name: Run NPM
      #   run: |
      #     npm run all
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/config/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

